site_name: Foretify用户指南
site_description: 本文档为软件工具提供详细的介绍、安装指南、使用流程、操作方法及故障排除信息。
site_author: 你的名字

theme:
  name: material
  # name: readthedocs
  features:
    - navigation.instant
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - header.autohide
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.follow
  palette:
    primary: 'indigo'
    accent: 'light blue'
  logo: assets/Logo.png
  favicon: assets/favicon.ico
  font:
    text: 'Roboto'  # 文本字体
    code: 'Roboto Mono'  # 代码字体
  language: 'zh'
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

nav:
  - 用户指南: pages/index.md
  # - 相关术语: pages/reference/glossary.md
  - 产品介绍:
      - 产品概述: pages/product/product_overview.md
      - 快速开始: 
          - SDV流程: pages/tutorials/workflow.md
          - 快速开始: 
            - 如何通过Foretify Developer启动一次简单的测试: pages/tutorials/quick_started - Foretify Developer.md
            - Foretify Manager简介: pages/product/fmanuser_intro.md
            # - 查看测试定义: pages/tutorials/review_tests.md
            # - 测试组执行（泛化）: pages/tutorials/run_test_suites.md
            # - 创建工作区: pages/tutorials/create_workspace.md
            # - 分析测试结果: pages/tutorials/triage.md
            # - 分析覆盖率和性能指标: pages/tutorials/analyze_metrics.md

  - 安装指南: 
      - 安装须知: pages/setup/deployment.md
      - 许可证安装: pages/setup/license_server_installation.md
      - Foretify Developer安装: pages/setup/foretify_developer_installation.md
      - Foretify Manager安装: pages/setup/foretify_manager_installation.md
      - 仿真器配置: pages/setup/simulator_configuration.md
  - 集成说明: pages/Integration/Integration.md
  - Foretellix官网: https://www.foretellix.com
  - Bilibili官方账号: https://space.bilibili.com/531249396

plugins:
  - search
  - git-revision-date-localized:
      enable_version: true
      enable_relative: true
      enable_timezone: true
  - glightbox
  # - social:
  #     # cards_layout: default/variant
  #     cards_layout_options:
  #       background_image: layouts/background.png
  #       background_color: transparent

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - def_list


extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/custom.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# repo_url: https://github.com/yourusername/your-repository
# repo_name: GitHub
